layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

social_media:
  github: Geezus42
  # behance: your_username
  dev: geezus42
  discord: Geezus42
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  keybase: Geezus_42
  linkedin: jeremy-r-036943149
  mastodon: Geezus42
  matrix: Geezus42:matrix.org
  # medium: your_username
  signal: Geezus42
  # stackoverflow: your_user_id
  telegram: Geezus42
  twitter: Geezustx
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Arch
    web_url: https://github.com/topics/arch
    image_url: https://raw.githubusercontent.com/github/explore/7b8474be525e3f210d3c8d60a32beca4bfc2895b/topics/archlinux/archlinux.png

  - name: Automation
    web_url: https://github.com/topics/automation

  - name: Bash
    web_url: https://github.com/topics/bash
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/bash/bash.png

  - name: Command line interface
    web_url: https://github.com/topics/cli

  - name: Containers
    web_url: https://github.com/topics/containers

  - name: Git
    web_url: https://github.com/topics/git
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/git/git.png

  - name: Firefox
    weburl: https://github.com/topics/firefox
    image_url: https://raw.githubusercontent.com/github/explore/728542e0d33f83720614f61923a9cb424264db23/topics/firefox/firefox.png

  - name: Home Assistant
    weburl: https://github.com/topics/homeassistant
    image_url: https://raw.githubusercontent.com/github/explore/1c6590bcecae757172108275aedd0b75680d8f1a/topics/home-assistant/home-assistant.png

  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/linux/linux.png

  - name: Markdown
    web_url: https://github.com/topics/markdown
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/markdown/markdown.png

  - name: Matrix
    web_url: https://github.com/topics/matrix
    image_url: https://avatars.githubusercontent.com/u/13446337?s=200&v=4

  - name: Neovim
    web_url: https://github.com/topics/neovim
    image_url: https://raw.githubusercontent.com/github/explore/26674e638508ac4a4e113ee32d6755ebfa000569/topics/neovim/neovim.png

  - name: NixOS
    web_url: https://github.com/topics/nix
    image_url: https://raw.githubusercontent.com/github/explore/321fcda5aea097657efeed8566610d1c0937a3bb/topics/nix/nix.png

  - name: Obsidian
    web_url: https://github.com/topics/obsidian-md
    image_url: https://raw.githubusercontent.com/github/explore/69803791d4c648dc3ebf8f12a1448d5a1fec0036/topics/obsidian-md/obsidian-md.png

  - name: Orchestration
    web_url: https://github.com/topics/orchestration

  - name: Pi-hole
    web_url: https://github.com/topics/pihole
    image_url: https://raw.githubusercontent.com/github/explore/d90dc858dc489cd2bc3b3295e71e04b4e2e2db00/topics/pihole/pihole.png

  - name: Raspberry Pi
    web_url: https://github.com/topics/raspberry-pi
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/raspberry-pi/raspberry-pi.png

  - name: Security
    web_url: https://github.com/topics/security

  - name: Software Defined Networking
    web_url: https://github.com/topics/sdn

  - name: Terminal
    web_url: https://github.com/topics/terminal
    image_url: https://raw.githubusercontent.com/github/explore/d92924b1d925bb134e308bd29c9de6c302ed3beb/topics/terminal/terminal.png

  - name: VScode
    web_url: https://github.com/topics/vscode
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/visual-studio-code/visual-studio-code.png

